#!/usr/bin/env bash
# Bookmark-Organizer launcher: pull DATABASE_URL from Vaultwarden, build+deploy
# the frontend, and start the API. Run from the repo root (/tmp/bookmark-organizer-host).
set -euo pipefail

cd "$(dirname "$0")"

# --- Pull secrets from Vaultwarden (item "Coffee Talk API Keys" holds Bookmark DB URL) ---
export PATH="$HOME/.local/bin:$PATH"
export NODE_TLS_REJECT_UNAUTHORIZED=0
VAULT_ITEM_NAME="Coffee Talk API Keys"

if ! bwv get item "$VAULT_ITEM_NAME" >/tmp/bmo_vault_item.json 2>/dev/null; then
  echo "ERROR: could not read Vaultwarden item '$VAULT_ITEM_NAME' (session locked? run: bwv unlock --raw > /home/mcqueen/.bw_session.txt)" >&2
  exit 1
fi

# Map vault field names -> env var names the api-server reads, as export statements.
python3 - <<'PY'
import json
item = json.load(open('/tmp/bmo_vault_item.json'))
mapping = {
  'Bookmark DB URL': 'DATABASE_URL',
}
out = []
for f in item.get('fields', []):
    envk = mapping.get(f.get('name'))
    if envk:
        val = f.get('value', '')
        out.append(f"export {envk}={val!r}")
open('/tmp/bmo_vault_env.sh','w').write("\n".join(out)+"\n")
PY

set -a
. /tmp/bmo_vault_env.sh
set +a
rm -f /tmp/bmo_vault_item.json /tmp/bmo_vault_env.sh

# Also write to a gitignored .env so dotenv (loaded by index.ts at startup) picks
# them up from disk — robust against shell->node env inheritance being unreliable.
bwv get item "$VAULT_ITEM_NAME" 2>/dev/null > /tmp/bmo_vault_item2.json
python3 - <<'PY'
import json
item = json.load(open('/tmp/bmo_vault_item2.json'))
mapping = { 'Bookmark DB URL': 'DATABASE_URL' }
lines = ["# Generated by start-bookmark.sh from Vaultwarden — gitignored, do not edit by hand.",
         "PORT=3002", "NODE_ENV=production"]
for f in item.get('fields', []):
    envk = mapping.get(f.get('name'))
    if envk:
        lines.append(f"{envk}={f.get('value','')}")
open('.env', 'w').write("\n".join(lines) + "\n")
PY
rm -f /tmp/bmo_vault_item2.json

echo "Secrets loaded from Vaultwarden."

# --- Build + deploy frontend (clean full copy so it can't desync) ---
FRONTEND_DIR="artifacts/bookmark-manager"
DEPLOY_DIR="/tmp/bookmark-app"
if [ -d "$FRONTEND_DIR" ]; then
  echo "Building frontend..."
  (cd "$FRONTEND_DIR" && PORT=5173 BASE_PATH=/ NODE_ENV=production pnpm run build) \
    || echo "WARN: frontend build failed — deploying last good dist if present"
  if [ -d "$FRONTEND_DIR/dist/public" ]; then
    echo "Deploying frontend to $DEPLOY_DIR ..."
    rm -rf "$DEPLOY_DIR/assets" "$DEPLOY_DIR/index.html" "$DEPLOY_DIR/favicon.png" \
           "$DEPLOY_DIR/favicon.svg" "$DEPLOY_DIR/opengraph.jpg" "$DEPLOY_DIR/robots.txt"
    cp -r "$FRONTEND_DIR/dist/public/." "$DEPLOY_DIR/"
    echo "Frontend deployed."
  else
    echo "WARN: $FRONTEND_DIR/dist/public missing — leaving existing deploy untouched."
  fi
else
  echo "WARN: frontend dir $FRONTEND_DIR not found — skipping frontend deploy."
fi

echo "Secrets loaded from Vaultwarden. Starting API on PORT=${PORT:-3002}..."
set -a
. ./.env
set +a
exec node --enable-source-maps artifacts/api-server/dist/index.mjs
